export { makePalette } from './palette.js';
export type { PaletteName } from './palette.js';
export { prepareCanvas, normalizeDb } from './canvas.js';
export type { CanvasSurface } from './canvas.js';
export { Viewport } from './viewport.js';
export type { ViewRange } from './viewport.js';
export { drawWaveform, waveformColumns } from './waveform.js';
export type { WaveformOptions, WaveformColumn } from './waveform.js';
export { drawSpectrum, spectrumColumns } from './spectrum.js';
export type { SpectrumOptions } from './spectrum.js';
export { drawSpectrogram, spectrogramPixels } from './spectrogram.js';
export type { SpectrogramOptions } from './spectrogram.js';
